version: "3"

services:
  db:
    container_name: pedu-db
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
